const educationalContent = {
  "Non-verbal": {
    "Pronunciation": [
      {"id": "nv_pron_1", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Ahhh", "answer": "Ahhh", "choices": null, "icon": "😮"},
      {"id": "nv_pron_2", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Oooo", "answer": "Oooo", "choices": null, "icon": "😲"},
      {"id": "nv_pron_3", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Mmmm", "answer": "Mmmm", "choices": null, "icon": "😋"},
      {"id": "nv_pron_4", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Eeee", "answer": "Eeee", "choices": null, "icon": "😁"},
      {"id": "nv_pron_5", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Shhh", "answer": "Shhh", "choices": null, "icon": "🤫"},
      {"id": "nv_pron_6", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Moo", "answer": "Moo", "choices": null, "icon": "🐮"},
      {"id": "nv_pron_7", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Baa", "answer": "Baa", "choices": null, "icon": "🐑"},
      {"id": "nv_pron_8", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Meow", "answer": "Meow", "choices": null, "icon": "🐱"},
      {"id": "nv_pron_9", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Woof", "answer": "Woof", "choices": null, "icon": "🐶"},
      {"id": "nv_pron_10", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Cluck", "answer": "Cluck", "choices": null, "icon": "🐔"},
      {"id": "nv_pron_11", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Vroom", "answer": "Vroom", "choices": null, "icon": "🚗"},
      {"id": "nv_pron_12", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Choo Choo", "answer": "Choo Choo", "choices": null, "icon": "🚂"},
      {"id": "nv_pron_13", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Beep Beep", "answer": "Beep Beep", "choices": null, "icon": "🚕"},
      {"id": "nv_pron_14", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Buzz", "answer": "Buzz", "choices": null, "icon": "🐝"},
      {"id": "nv_pron_15", "prompt_ar": "استمع وحاول تقليد الصوت", "prompt_en": "Listen and try to copy the sound", "content": "Whoosh", "answer": "Whoosh", "choices": null, "icon": "💨"}
    ],
    "Reading_and_Writing": [
      {"id": "nv_rw_1", "prompt_ar": "تتبع الحرف", "prompt_en": "Trace the letter", "content": "A", "answer": "A", "choices": null, "icon": "🍎"},
      {"id": "nv_rw_2", "prompt_ar": "تتبع الحرف", "prompt_en": "Trace the letter", "content": "B", "answer": "B", "choices": null, "icon": "🐻"},
      {"id": "nv_rw_3", "prompt_ar": "تتبع الحرف", "prompt_en": "Trace the letter", "content": "C", "answer": "C", "choices": null, "icon": "🐱"},
      {"id": "nv_rw_4", "prompt_ar": "تتبع الحرف", "prompt_en": "Trace the letter", "content": "D", "answer": "D", "choices": null, "icon": "🐶"},
      {"id": "nv_rw_5", "prompt_ar": "تتبع الحرف", "prompt_en": "Trace the letter", "content": "E", "answer": "E", "choices": null, "icon": "🐘"},
      {"id": "nv_rw_6", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "F", "answer": "F", "choices": ["E", "F", "G"], "icon": "🐟"},
      {"id": "nv_rw_7", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "G", "answer": "G", "choices": ["G", "H", "I"], "icon": "🐐"},
      {"id": "nv_rw_8", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "H", "answer": "H", "choices": ["F", "G", "H"], "icon": "👒"},
      {"id": "nv_rw_9", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "I", "answer": "I", "choices": ["I", "J", "K"], "icon": "🧊"},
      {"id": "nv_rw_10", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "J", "answer": "J", "choices": ["H", "I", "J"], "icon": "🧃"},
      {"id": "nv_rw_11", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "K", "answer": "K", "choices": ["K", "L", "M"], "icon": "🪁"},
      {"id": "nv_rw_12", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "L", "answer": "L", "choices": ["J", "K", "L"], "icon": "🦁"},
      {"id": "nv_rw_13", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "M", "answer": "M", "choices": ["M", "N", "O"], "icon": "🌙"},
      {"id": "nv_rw_14", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "N", "answer": "N", "choices": ["L", "M", "N"], "icon": "🪹"},
      {"id": "nv_rw_15", "prompt_ar": "طابق الحرف بالصورة", "prompt_en": "Match the letter to the picture", "content": "O", "answer": "O", "choices": ["O", "P", "Q"], "icon": "🦉"}
    ]
  },
  "Minimal Speech": {
    "Pronunciation": [
      {"id": "ms_pron_1", "prompt_ar": "استمع وقل المقطع", "prompt_en": "Listen and say the sound", "content": "Ba-ba", "answer": "Ba-ba", "choices": null, "icon": "🐑"},
      {"id": "ms_pron_2", "prompt_ar": "استمع وقل المقطع", "prompt_en": "Listen and say the sound", "content": "Ma-ma", "answer": "Ma-ma", "choices": null, "icon": "👩"},
      {"id": "ms_pron_3", "prompt_ar": "استمع وقل المقطع", "prompt_en": "Listen and say the sound", "content": "Da-da", "answer": "Da-da", "choices": null, "icon": "👨"},
      {"id": "ms_pron_4", "prompt_ar": "استمع وقل المقطع", "prompt_en": "Listen and say the sound", "content": "Ka-ka", "answer": "Ka-ka", "choices": null, "icon": "🦅"},
      {"id": "ms_pron_5", "prompt_ar": "استمع وقل المقطع", "prompt_en": "Listen and say the sound", "content": "Ta-ta", "answer": "Ta-ta", "choices": null, "icon": "👋"},
      {"id": "ms_pron_6", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Up", "answer": "Up", "choices": null, "icon": "⬆️"},
      {"id": "ms_pron_7", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Go", "answer": "Go", "choices": null, "icon": "🟢"},
      {"id": "ms_pron_8", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Eat", "answer": "Eat", "choices": null, "icon": "🍽️"},
      {"id": "ms_pron_9", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "No", "answer": "No", "choices": null, "icon": "❌"},
      {"id": "ms_pron_10", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Yes", "answer": "Yes", "choices": null, "icon": "✅"},
      {"id": "ms_pron_11", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Hi", "answer": "Hi", "choices": null, "icon": "👋"},
      {"id": "ms_pron_12", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Bye", "answer": "Bye", "choices": null, "icon": "🚪"},
      {"id": "ms_pron_13", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "More", "answer": "More", "choices": null, "icon": "➕"},
      {"id": "ms_pron_14", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Cup", "answer": "Cup", "choices": null, "icon": "🥤"},
      {"id": "ms_pron_15", "prompt_ar": "استمع وقل الكلمة", "prompt_en": "Listen and say the word", "content": "Ball", "answer": "Ball", "choices": null, "icon": "⚽"}
    ],
    "Reading_and_Writing": [
      {"id": "ms_rw_1", "prompt_ar": "تتبع الكلمة", "prompt_en": "Trace the word", "content": "Sun", "answer": "Sun", "choices": null, "icon": "☀️"},
      {"id": "ms_rw_2", "prompt_ar": "تتبع الكلمة", "prompt_en": "Trace the word", "content": "Cat", "answer": "Cat", "choices": null, "icon": "🐱"},
      {"id": "ms_rw_3", "prompt_ar": "تتبع الكلمة", "prompt_en": "Trace the word", "content": "Dog", "answer": "Dog", "choices": null, "icon": "🐶"},
      {"id": "ms_rw_4", "prompt_ar": "تتبع الكلمة", "prompt_en": "Trace the word", "content": "Bus", "answer": "Bus", "choices": null, "icon": "🚌"},
      {"id": "ms_rw_5", "prompt_ar": "تتبع الكلمة", "prompt_en": "Trace the word", "content": "Car", "answer": "Car", "choices": null, "icon": "🚗"},
      {"id": "ms_rw_6", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "_at", "answer": "H", "choices": ["H", "M", "S"], "icon": "🎩"},
      {"id": "ms_rw_7", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "B_s", "answer": "u", "choices": ["a", "e", "u"], "icon": "🚌"},
      {"id": "ms_rw_8", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "P_g", "answer": "i", "choices": ["a", "i", "o"], "icon": "🐷"},
      {"id": "ms_rw_9", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "_ow", "answer": "C", "choices": ["B", "C", "D"], "icon": "🐮"},
      {"id": "ms_rw_10", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "C_p", "answer": "u", "choices": ["a", "i", "u"], "icon": "🥤"},
      {"id": "ms_rw_11", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "_all", "answer": "B", "choices": ["B", "F", "T"], "icon": "⚽"},
      {"id": "ms_rw_12", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "B_ed", "answer": "B", "choices": ["R", "B", "T"], "icon": "🛏️"},
      {"id": "ms_rw_13", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "S_n", "answer": "u", "choices": ["a", "o", "u"], "icon": "☀️"},
      {"id": "ms_rw_14", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "T_p", "answer": "o", "choices": ["a", "e", "o"], "icon": "🔝"},
      {"id": "ms_rw_15", "prompt_ar": "ما هو الحرف الناقص؟", "prompt_en": "What is the missing letter?", "content": "P_n", "answer": "e", "choices": ["a", "e", "i"], "icon": "🖊️"}
    ]
  },
  "Verbal": {
    "Pronunciation": [
      {"id": "vb_pron_1", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I see a blue bird.", "answer": "I see a blue bird.", "choices": null, "icon": "🐦"},
      {"id": "vb_pron_2", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "The sun is hot today.", "answer": "The sun is hot today.", "choices": null, "icon": "☀️"},
      {"id": "vb_pron_3", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "Hello, how are you?", "answer": "Hello, how are you?", "choices": null, "icon": "👋"},
      {"id": "vb_pron_4", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I like to play outside.", "answer": "I like to play outside.", "choices": null, "icon": "⚽"},
      {"id": "vb_pron_5", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "My friend is nice.", "answer": "My friend is nice.", "choices": null, "icon": "👫"},
      {"id": "vb_pron_6", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "It is time to eat.", "answer": "It is time to eat.", "choices": null, "icon": "🍽️"},
      {"id": "vb_pron_7", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I want to read a book.", "answer": "I want to read a book.", "choices": null, "icon": "📖"},
      {"id": "vb_pron_8", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "The car goes fast.", "answer": "The car goes fast.", "choices": null, "icon": "🚗"},
      {"id": "vb_pron_9", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "Let's wash our hands.", "answer": "Let's wash our hands.", "choices": null, "icon": "🧼"},
      {"id": "vb_pron_10", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I feel happy today.", "answer": "I feel happy today.", "choices": null, "icon": "😊"},
      {"id": "vb_pron_11", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I can tie my shoes.", "answer": "I can tie my shoes.", "choices": null, "icon": "👟"},
      {"id": "vb_pron_12", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "The dog is running.", "answer": "The dog is running.", "choices": null, "icon": "🐕"},
      {"id": "vb_pron_13", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "We play at the park.", "answer": "We play at the park.", "choices": null, "icon": "🏞️"},
      {"id": "vb_pron_14", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "I sleep in my bed.", "answer": "I sleep in my bed.", "choices": null, "icon": "🛏️"},
      {"id": "vb_pron_15", "prompt_ar": "اقرأ الجملة بصوت عالٍ", "prompt_en": "Read the sentence out loud", "content": "It is raining outside.", "answer": "It is raining outside.", "choices": null, "icon": "🌧️"}
    ],
    "Reading_and_Writing": [
      {"id": "vb_rw_1", "prompt_ar": "اقرأ القصة ثم أجب: توم يلعب بالكرة. الكرة حمراء. ما لون الكرة؟", "prompt_en": "Read the story and answer: Tom plays with a ball. The ball is red. What color is the ball?", "content": "Tom plays with a ball. The ball is red.", "answer": "Red", "choices": ["Red", "Blue", "Green"], "icon": "🔴"},
      {"id": "vb_rw_2", "prompt_ar": "اقرأ القصة ثم أجب: سارة حزينة. صديقتها أعطتها عناقاً. كيف تشعر سارة الآن؟", "prompt_en": "Read the story and answer: Sarah is sad. Her friend gave her a hug. How does Sarah feel now?", "content": "Sarah is sad. Her friend gave her a hug.", "answer": "Better", "choices": ["Mad", "Sad", "Better"], "icon": "🫂"},
      {"id": "vb_rw_3", "prompt_ar": "اقرأ القصة ثم أجب: الكلب يركض في الحديقة. الكلب سعيد. أين يركض الكلب؟", "prompt_en": "Read the story and answer: The dog runs in the park. The dog is happy. Where does the dog run?", "content": "The dog runs in the park. The dog is happy.", "answer": "Park", "choices": ["House", "Store", "Park"], "icon": "🏞️"},
      {"id": "vb_rw_4", "prompt_ar": "اقرأ القصة ثم أجب: أمي تطبخ. الطعام رائحته طيبة. من يطبخ؟", "prompt_en": "Read the story and answer: Mom cooks. It smells good. Who cooks?", "content": "Mom cooks. It smells good.", "answer": "Mom", "choices": ["Dad", "Mom", "Boy"], "icon": "👩‍🍳"},
      {"id": "vb_rw_5", "prompt_ar": "اقرأ القصة ثم أجب: المطر يتساقط. سأرتدي حذائي. ماذا سأرتدي؟", "prompt_en": "Read the story and answer: Rain falls. I wear boots. What do I wear?", "content": "Rain falls. I wear boots.", "answer": "Boots", "choices": ["Hat", "Boots", "Scarf"], "icon": "👢"},
      {"id": "vb_rw_6", "prompt_ar": "اقرأ القصة ثم أجب: الولد ينام. إنه وقت الليل. متى ينام؟", "prompt_en": "Read the story and answer: Boy sleeps. It is night. When does he sleep?", "content": "Boy sleeps. It is night.", "answer": "Night", "choices": ["Day", "Night", "Morning"], "icon": "🌙"},
      {"id": "vb_rw_7", "prompt_ar": "اقرأ القصة ثم أجب: التفاحة حلوة. أنا آكلها. ما هو طعم التفاحة؟", "prompt_en": "Read the story and answer: Apple is sweet. I eat it. How does it taste?", "content": "Apple is sweet. I eat it.", "answer": "Sweet", "choices": ["Sour", "Sweet", "Salty"], "icon": "🍎"},
      {"id": "vb_rw_8", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "apple / eat / I / an", "answer": "I eat an apple", "choices": ["eat an I apple", "I eat an apple", "apple I eat an"], "icon": "🍎"},
      {"id": "vb_rw_9", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "cat / is / the / sleeping", "answer": "The cat is sleeping", "choices": ["sleeping the cat is", "The cat is sleeping", "cat sleeping is the"], "icon": "🐈"},
      {"id": "vb_rw_10", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "to / want / play / I", "answer": "I want to play", "choices": ["I want to play", "play I to want", "want to play I"], "icon": "⚽"},
      {"id": "vb_rw_11", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "hand / hold / my / please", "answer": "Please hold my hand", "choices": ["hold my hand please", "Please hold my hand", "my hand please hold"], "icon": "🤝"},
      {"id": "vb_rw_12", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "friend / my / is / tall", "answer": "My friend is tall", "choices": ["tall is my friend", "My friend is tall", "is tall friend my"], "icon": "🧍"},
      {"id": "vb_rw_13", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "book / read / the / I", "answer": "I read the book", "choices": ["I read the book", "read I the book", "book the read I"], "icon": "📖"},
      {"id": "vb_rw_14", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "coat / put / your / on", "answer": "Put on your coat", "choices": ["on your coat put", "Put on your coat", "your coat on put"], "icon": "🧥"},
      {"id": "vb_rw_15", "prompt_ar": "رتب الكلمات لتكوين جملة", "prompt_en": "Unscramble the words to make a sentence", "content": "sun / the / bright / is", "answer": "The sun is bright", "choices": ["bright is sun the", "The sun is bright", "is bright the sun"], "icon": "☀️"}
    ]
  },
  "Tech-Assisted": {
    "Pronunciation": [
      {"id": "ta_pron_1", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Want", "answer": "Want", "choices": null, "icon": "🤲"},
      {"id": "ta_pron_2", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Help", "answer": "Help", "choices": null, "icon": "🙋"},
      {"id": "ta_pron_3", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Bathroom", "answer": "Bathroom", "choices": null, "icon": "🚽"},
      {"id": "ta_pron_4", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Eat", "answer": "Eat", "choices": null, "icon": "🍽️"},
      {"id": "ta_pron_5", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Stop", "answer": "Stop", "choices": null, "icon": "🛑"},
      {"id": "ta_pron_6", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "More", "answer": "More", "choices": null, "icon": "➕"},
      {"id": "ta_pron_7", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Sleep", "answer": "Sleep", "choices": null, "icon": "😴"},
      {"id": "ta_pron_8", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Play", "answer": "Play", "choices": null, "icon": "🧸"},
      {"id": "ta_pron_9", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Drink", "answer": "Drink", "choices": null, "icon": "🚰"},
      {"id": "ta_pron_10", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Yes", "answer": "Yes", "choices": null, "icon": "👍"},
      {"id": "ta_pron_11", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "No", "answer": "No", "choices": null, "icon": "👎"},
      {"id": "ta_pron_12", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Pain", "answer": "Pain", "choices": null, "icon": "🤕"},
      {"id": "ta_pron_13", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Hungry", "answer": "Hungry", "choices": null, "icon": "😋"},
      {"id": "ta_pron_14", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Thirsty", "answer": "Thirsty", "choices": null, "icon": "🥤"},
      {"id": "ta_pron_15", "prompt_ar": "انقر على الرمز واسمع الكلمة", "prompt_en": "Tap the icon and hear the word", "content": "Wait", "answer": "Wait", "choices": null, "icon": "⏳"}
    ],
    "Reading_and_Writing": [
      {"id": "ta_rw_1", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I want apple", "answer": "I want apple", "choices": ["Apple I want", "I want apple", "Want I apple"], "icon": "🍎"},
      {"id": "ta_rw_2", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I need help", "answer": "I need help", "choices": ["I need help", "Help I need", "Need I help"], "icon": "🤝"},
      {"id": "ta_rw_3", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I am hungry", "answer": "I am hungry", "choices": ["Hungry am I", "Am I hungry", "I am hungry"], "icon": "🍽️"},
      {"id": "ta_rw_4", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I want to play", "answer": "I want to play", "choices": ["Play I want to", "I want to play", "Want to play I"], "icon": "🧸"},
      {"id": "ta_rw_5", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I feel happy", "answer": "I feel happy", "choices": ["Happy I feel", "I feel happy", "Feel I happy"], "icon": "😊"},
      {"id": "ta_rw_6", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I want water", "answer": "I want water", "choices": ["I want water", "Water want I", "Want I water"], "icon": "💧"},
      {"id": "ta_rw_7", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I need bathroom", "answer": "I need bathroom", "choices": ["Bathroom need I", "I need bathroom", "Need I bathroom"], "icon": "🚽"},
      {"id": "ta_rw_8", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I feel sad", "answer": "I feel sad", "choices": ["I feel sad", "Sad feel I", "Feel I sad"], "icon": "😢"},
      {"id": "ta_rw_9", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I want more", "answer": "I want more", "choices": ["More want I", "I want more", "Want I more"], "icon": "➕"},
      {"id": "ta_rw_10", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "Stop please", "answer": "Stop please", "choices": ["Please stop", "Stop please", "Stop I please"], "icon": "🛑"},
      {"id": "ta_rw_11", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I am thirsty", "answer": "I am thirsty", "choices": ["Thirsty am I", "I am thirsty", "Am I thirsty"], "icon": "🥤"},
      {"id": "ta_rw_12", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I feel tired", "answer": "I feel tired", "choices": ["Tired feel I", "I feel tired", "Feel I tired"], "icon": "🥱"},
      {"id": "ta_rw_13", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I want sleep", "answer": "I want sleep", "choices": ["I want sleep", "Sleep want I", "Want sleep I"], "icon": "😴"},
      {"id": "ta_rw_14", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "Let's go home", "answer": "Let's go home", "choices": ["Home let's go", "Let's go home", "Go home let's"], "icon": "🏠"},
      {"id": "ta_rw_15", "prompt_ar": "رتب الرموز لتكوين جملة", "prompt_en": "Arrange the icons to make a sentence", "content": "I like this", "answer": "I like this", "choices": ["This like I", "I like this", "Like this I"], "icon": "👍"}
    ]
  }
};